//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORy
    {
        public int CAT_ID { get; set; }
        public string CATNAME { get; set; }
        public int CAT_STATUS { get; set; }
    }
}
