//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIDETAIL
    {
        public long PID_ID { get; set; }
        public long PID_PURCHASEID { get; set; }
        public int PID_PROID { get; set; }
    
        public virtual PURCHASEINVOICE PURCHASEINVOICE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
