//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.PIDETAILS = new HashSet<PIDETAIL>();
            this.STOCKs = new HashSet<STOCK>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
        public string PRO_BARCODE { get; set; }
        public Nullable<System.DateTime> PRO_EXPIRYDATE { get; set; }
        public Nullable<decimal> PRO_BUYINGPRICE { get; set; }
        public Nullable<decimal> PRO_SELLINGPRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIDETAIL> PIDETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCKs { get; set; }
    }
}
