//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int U_ID { get; set; }
        public string U_NAME { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_PHONE { get; set; }
        public string U_EMAIL { get; set; }
        public byte U_STATUS { get; set; }
        public int U_ROLEID { get; set; }
    
        public virtual role role { get; set; }
    }
}
